services:
  - type: web
    name: omnihub
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node --experimental-sqlite index.js
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: PORT
        value: 5200
      - key: OMNIHUB_SECRET
        generateValue: true
